name: CI/CD Pipeline for Carousel API

on: 
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true 

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests and generate coverage report
        run: |
          coverage run --source=carousel_api -m unittest discover -s tests
          coverage report -m
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ '56d29ad3-d20c-488a-af76-91267bb93f95' }}     
          file: ./coverage.xml                    
          flags: unittests                         
          name: codecov-umbrella                   
          fail_ci_if_error: true  

  build:
    runs-on: ubuntu-latest
    needs: test-and-coverage  # This job depends on the previous one

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/