name: CI/CD Pipeline for Carousel API

on: 
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]

jobs:
  test-and-coverage:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install pytest pytest-cov

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ '56d29ad3-d20c-488a-af76-91267bb93f95' }}  

      - name: Instalar Bandit (análisis de seguridad)
        run: pip install bandit

      - name: Ejecutar Bandit (análisis de seguridad de código)
        run: bandit -r . -x venv,dist,build --exit-zero

      - name: Instalar pip-audit (auditoría de dependencias)
        run: pip install pip-audit

      - name: Ejecutar pip-audit (auditoría de dependencias)
        run: pip-audit --exit-code 1

  build:
    runs-on: ubuntu-latest
    needs: test-and-coverage  # This job depends on the previous one

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/