name: CI/CD Pipeline for Carousel API

on: 
  push:
    branches: [ main ]  # Ejecutar el workflow en cada push a la rama 'main'
  pull_request:
    branches: [ main ]  # También ejecutar en pull requests a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Sistema operativo en el que se ejecutará el trabajo
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      
    steps:
      - uses: actions/checkout@v3  # Descargar el código del repositorio

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'  # Especifica la versión de Python que usas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (opcional)
        run: |
          python -m unittest discover -s tests  # Ejecuta las pruebas unitarias (si las tienes)

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload artifacts (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/